### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/faucet#4]
Following the instructions in the readme, running `docker-compose up` returns:

```bash
→ docker-compose up
Building faucet-server
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 80, in _execute
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-osxkeychain', 'list']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 260, in build
  File "site-packages/docker/api/build.py", line 307, in _set_auth_headers
  File "site-packages/docker/auth.py", line 302, in get_all_credentials
  File "site-packages/dockerpycreds/store.py", line 71, in list
  File "site-packages/dockerpycreds/store.py", line 93, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-osxkeychain exited with "The specified item could not be found in the keychain.".
[58046] Failed to execute script docker-compose
```

Looks like some specific item in the macOS keychain is needed?

Or is my Docker too edgy?

<img width="848" alt="screen shot 2019-02-13 at 21 15 30" src="https://user-images.githubusercontent.com/90316/52740961-8e63fb00-2fd4-11e9-82a2-a2593f9ccaaf.png">

**Comment by kremalicious** [comment]
working with stable Docker and recent changes in `master`
